<?php

namespace Api\V1\Http\Controllers\Enet;

use Illuminate\Http\Request;

class EnetEventTipController  extends BaseController
{
    /**
     * @param Request $request
     * @param $event_id
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    public function tips(Request $request, $event_id)
    {
        $data['where']['event_id'] = $event_id;
        $data['all'] = true;
        $data['columns']= [
            'id',
            'user_id',
            'event_id',
            'sport_id',
            'odds_type_id',
            'odds_id',
            'odds',
            'tip_amount',
            'point',
            'score',
            'result_status',
            'result_validation',
            'provider',
            'sport_readable_id',
            'league_name',
            'odds_type_name',
            'odds_name',
            'home_name',
            'away_name',
            'event_started_at',
            'event_ends_at',
            'validated_at',
            'validation_details',
        ];
        $request->merge($data);
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}
