<?php

namespace Api\V1\Http\Controllers\Enet;

use Illuminate\Http\Request;

class EnetEventStatisticController  extends BaseController
{
    /**
     * @param Request $request
     * @param $event_id
     * @return \Illuminate\Http\JsonResponse
     */
    public function statistics(Request $request, $event_id)
    {
        $data['where']['enet_id'] = $event_id;
        $data['all'] = true;
        $data['columns']= [
            'id',
            'enet_id',
            'standing_id',
            'rank',
            'points',
            'name',
            'first_name',
            'last_name',
        ];
        $request->merge($data);
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}
