<?php

namespace Api\V1\Http\Controllers\Enet;

use Illuminate\Http\Request;

class EnetTournamentTemplateController  extends BaseController
{
    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     * @throws \Illuminate\Contracts\Container\BindingResolutionException
     */
    public function index(Request $request)
    {
        $data = [
            'order_by' => [
                'name' => 'asc',
            ],
            'all' => true,
            'columns' => [
                'name',
                'id',
                'readable_id',
                'sport_id',
                'gender',
            ],
            'with' => [
                'sport' => [
                    'columns' => [
                        'name',
                        'id',
                        'readable_id',
                    ]
                ]
            ],
            'where_has' => [
               'sport' => [
                   'where' => [
                       'is_active' => \ConstYesNo::YES
                   ]
               ]
            ]
        ];
        $request->merge($data);
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}
