<?php

namespace Api\V1\Http\Controllers\Enet;

use Illuminate\Http\Request;

class EnetSportController extends BaseController
{
    /**
     * @param Request $request
     * @return \Illuminate\Http\JsonResponse
     */
    public function activeSports(Request $request)
    {
        $data['where']['is_active'] = \ConstYesNo::YES;
        $data['all'] = true;
        $data['order_by'] = 'position';
        $data['columns']= [
            'name',
            'id',
            'readable_id',
            'is_mobile',
            'image_path',
            'image_disk',
            'discover_path',
            'discover_disk',
        ];
        $request->merge($data);
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}
