<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;

class MetasTableSeeder extends Seeder
{

    /**
     * Auto generated seed file
     *
     * @return void
     */
    public function run()
    {


        \DB::table('metas')->delete();

        \DB::table('metas')->insert(array (
            0 =>
            array (
                'id' => 4,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 0,
                'attribute' => 'name',
                'attribute_value' => 'referrer',
                'default_content' => NULL,
                'created_at' => '2019-07-03 17:23:09',
                'updated_at' => '2019-07-03 17:23:09',
                'deleted_at' => NULL,
            ),
            1 =>
            array (
                'id' => 27,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 0,
                'attribute' => 'name',
                'attribute_value' => 'application-name',
                'default_content' => NULL,
                'created_at' => '2019-07-17 18:09:16',
                'updated_at' => '2019-07-17 18:09:16',
                'deleted_at' => NULL,
            ),
            2 =>
            array (
                'id' => 28,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 0,
                'attribute' => 'name',
                'attribute_value' => 'google-play-app',
                'default_content' => NULL,
                'created_at' => '2019-07-17 18:11:33',
                'updated_at' => '2019-07-17 18:17:02',
                'deleted_at' => NULL,
            ),
            3 =>
            array (
                'id' => 29,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 0,
                'attribute' => 'name',
                'attribute_value' => 'apple-itunes-app',
                'default_content' => NULL,
                'created_at' => '2019-07-17 18:16:16',
                'updated_at' => '2019-07-17 18:16:16',
                'deleted_at' => NULL,
            ),
            4 =>
            array (
                'id' => 30,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'property',
                'attribute_value' => 'locale',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            5 =>
            array (
                'id' => 31,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'property',
                'attribute_value' => 'type',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            6 =>
            array (
                'id' => 33,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'property',
                'attribute_value' => 'url',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            7 =>
            array (
                'id' => 35,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'property',
                'attribute_value' => 'image',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            8 =>
            array (
                'id' => 36,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'property',
                'attribute_value' => 'site_name',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            9 =>
            array (
                'id' => 37,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'property',
                'attribute_value' => 'app_id',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            10 =>
            array (
                'id' => 38,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'card',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            11 =>
            array (
                'id' => 39,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'site',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            12 =>
            array (
                'id' => 40,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'creator',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            13 =>
            array (
                'id' => 41,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'title',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            14 =>
            array (
                'id' => 42,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'description',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            15 =>
            array (
                'id' => 43,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'image',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            16 =>
            array (
                'id' => 44,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'Title',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            17 =>
            array (
                'id' => 45,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'Subject',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            18 =>
            array (
                'id' => 46,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'Contributor',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            19 =>
            array (
                'id' => 47,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'Description',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
            20 =>
            array (
                'id' => 48,
                'is_required' => 0,
                'min' => NULL,
                'max' => NULL,
                'is_required_in_group' => 0,
                'is_active' => 1,
                'only_in_groups' => 1,
                'attribute' => 'name',
                'attribute_value' => 'capable',
                'default_content' => NULL,
                'created_at' => '2019-09-24 00:14:53',
                'updated_at' => '2019-09-24 00:14:53',
                'deleted_at' => NULL,
            ),
        ));

    }
}
