<?php

namespace Api\V1\Http\Controllers;

use Illuminate\Http\Request;

class CompetitionController extends BaseController
{
    public function index(Request $request)
    {
        $request->merge([
            'order_by' => 'order',
            'with' => [
                'sports:enet_sports.id,name',
                'tournament_stages:enet_tournament_stages.id,name',
            ],

        ]);

        return parent::index($request); // TODO: Change the autogenerated stub
    }

    /**
     * @param Request $request
     * @param $slug
     * @return \Illuminate\Http\JsonResponse
     */
    public function showBySlug(Request $request, $slug)
    {
        $item = $this->service->findByArray($slug, $request->all(), 'slug');
        if ($item) {
            $response = $this->transformer->transform($item, $request, 'transformSingle');
            return $this->response->success($response);
        } else {
            $message = $this->message('not_found', ['item' => $this->resource_name, 'id' => $slug]);
            $code = laraarea_api_error_code('not_found');
            return $this->response->notFoundItem($request, $code, $message);
        }
    }
}
