<?php

namespace Api\V1\Http\Controllers;

use Illuminate\Http\Request;

class IapController extends BaseController
{
    public function index(Request $request)
    {
        $request->merge([
            'first' => true
        ]);
        return parent::index($request); // TODO: Change the autogenerated stub
    }
}
