<?php

namespace Api\V1\Services;

use Illuminate\Pagination\LengthAwarePaginator;
use Illuminate\Support\Collection;
use Traits\Services\NotificationServiceTrait;

class NotificationService extends BaseService
{
    use NotificationServiceTrait;

    public function index($data)
    {
        $items = parent::index($data); // TODO: Change the autogenerated stub
        if (is_a($items, Collection::class) || is_a($items, LengthAwarePaginator::class)) {
            $this->setUserData($items, $this->getAuth());
        }
        return $items;
    }
}
